- hosts: centos
  remote_user: root

  tasks:
    - name: install nginx
      yum: name=nginx
    - name: copy nginx.conf
      copy: src=./nginx.conf  dest=/etc/nginx/nginx.conf backup=yes
    - name: create dir
      file: name=/usr/share/nginx state=directory
      file: name=/usr/share/nginx/logs state=directory
      file: name=/usr/share/nginx/logs/access state=directory

    - name: start nginx service
      service: name=nginx state=started enabled=yes
