- hosts: all
  remote_user: root

  tasks:
    # - name: install haproxy
    #   yum: name=haproxy
    # - name: copy nginx.conf
    #   copy: src=~/config/ansible/playbook/centos/nginx/nginx.conf  dest=/etc/nginx/nginx.conf backup=yes
    # - name: create dir
    #   file: name=/usr/share/nginx state=directory
    #   file: name=/usr/share/nginx/logs state=directory
    #   file: name=/usr/share/nginx/logs/access state=directory

    - name: start service
      service: name=nginx state=started enabled=yes

    - name: shell命令
      ansible.builtin.shell: echo 123 > /tmp/123

    # - name: Disable SELinux
    #   ansible.posix.selinux:
    #     state: disabled

    # - name: do not permit traffic in default zone on port 80/tcp
    #   ansible.posix.firewalld:
    #     port: 6379/tcp
    #     permanent: true
    #     state: enabled
    #     # state: disabled
    # - name: restart firewalld
    #   service: name=firewalld state=restarted
