- hosts: all
  remote_user: root

  # 自定义变量
  vars:
    varname: zsh
    varname2: fish

  tasks:
    - name: install mysql-utilities
      yum: name=mysql-utilities
    # - name: copy nginx.conf
    #   copy: src=~/config/ansible/playbook/centos/nginx/nginx.conf  dest=/etc/nginx/nginx.conf backup=yes
    # - name: create dir
    #   file: name=/usr/share/nginx state=directory
    #   file: name=/usr/share/nginx/logs state=directory
    #   file: name=/usr/share/nginx/logs/access state=directory

    # - name: start service
    #   service: name=nginx state=started enabled=yes

    # - name: start mysqld_exporter
    #   systemd_service:
    #     name: mysqld_exporter
    #     state: started
    #     enabled: true
    #     daemon_reload: true

    # - name: 将sql文件复制下来
    #   fetch: "src=/root/test.sql dest=/tmp/test.sql"

    # - name: shell命令
    #   shell: echo 123 > /tmp/123
    #
    # - name: shell命令
    #   shell: echo 123 > 123
    #   args:
    #     chdir: /tmp

    # - name: 下载kafka
    #   shell: wget --no-check-certificate https://archive.apache.org/dist/kafka/3.0.0/kafka_2.12-3.0.0.tgz
    #   args:
    #     chdir: /tmp

    # - name: 复制kafka
    #   fetch: "src=/tmp/kafka_2.12-3.0.0.tgz dest=/tmp/kafka_2.12-3.0.0.tgz"
    #
    # - name: 解压
    #   unarchive:
    #     src: /tmp/kafka_2.12-3.0.0.tgz
    #     dest: /usr/local/

    # - name: Disable SELinux
    #   ansible.posix.selinux:
    #     state: disabled

    # - name: do not permit traffic in default zone on port 80/tcp
    #   ansible.posix.firewalld:
    #     port: 6379/tcp
    #     permanent: true
    #     state: enabled
    #     # state: disabled
    # - name: restart firewalld
    #   service: name=firewalld state=restarted
