- hosts: 192.168.110.5
  remote_user: root

  tasks:
    - name: install haproxy
      yum: name=haproxy
    - name: copy haproxy.conf
      copy: src=./haproxy.cfg  dest=/etc/haproxy/haproxy.cfg backup=yes
    - name: start haproxy service
      service: name=haproxy state=started enabled=yes
