# MASTER
- hosts: 192.168.110.4
  remote_user: root

  tasks:
    - name: install keepalived
      yum: name=keepalived

    - name: copy config file
      copy: src=./keepalived-redis-MASTER.conf  dest=/etc/keepalived/keepalived.conf backup=yes

    - name: copy redis_check.sh
      copy: src=./redis_check.sh  dest=/etc/keepalived/redis_check.sh backup=yes

    - name: start service
      service: name=keepalived state=started enabled=yes

# BACKUP
- hosts: 192.168.110.5
  remote_user: root

  tasks:
    - name: install keepalived
      yum: name=keepalived

    - name: copy config file
      copy: src=./keepalived-redis-BACKUP.conf  dest=/etc/keepalived/keepalived.conf backup=yes

    - name: copy redis_check.sh
      copy: src=./redis_check.sh  dest=/etc/keepalived/redis_check.sh backup=yes

    - name: start service
      service: name=keepalived state=started enabled=yes
